GatewayBelizeOn/Controllers/ZitroController.cs
using GatewayBelizeOn.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace GatewayBelizeOn.Controllers
{
    public class ZitroController : Controller
    {
        //Variable to manage the instance of the EntityFramework.
        private belizeonEntities _belizeonEntities = new belizeonEntities();
        
        /// <summary>
        /// Method to validate if the sessions is active.
        /// </summary>
        /// <returns>View</returns>
        [HttpGet]
        public ActionResult Index()
        {
            String userName = (string)(Session["userZitro"]);
            if (userName == "" || userName == null)
            {
                return View();
            }
            else
            {
                return View("../Orders/Index");
            }            
        }

        /// <summary>
        /// Method to verify if the user exist in our databases with the given user y password
        /// </summary>
        /// <param name="loginData">Object with the neccesaries fields to login the user</param>
        /// <returns>Json</returns>
        [HttpPost]
        public JsonResult verifyUSer(Account loginData)
        {
            try
            {
                string crypt = Encrypter.EncryptSHA256(loginData.password);
                var expireTime = DateTime.Now.AddMinutes(30);

                BON_USR_USERS user = this.getUserValidate(loginData.userName, crypt);
                if (user != null)
                {
                    Session["userZitro"] = loginData.userName;
                    Session["expireZitroUser"] = expireTime;
                    return Json(new HttpStatusCodeResult(System.Net.HttpStatusCode.OK, user.userName), JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new HttpStatusCodeResult(System.Net.HttpStatusCode.Unauthorized,"User or Password Invalid please try again"), JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new HttpStatusCodeResult(System.Net.HttpStatusCode.InternalServerError, "We have some problems with our site, please try again later"), JsonRequestBehavior.AllowGet);
            }
        }


        /// <summary>
        /// Method to consume the Databases with entity framework
        /// </summary>
        /// <param name="userName">username</param>
        /// <param name="password">password</param>
        /// <returns>BON_USR_USERS</returns>
        private BON_USR_USERS getUserValidate(string userName, string password)
        {
            return _belizeonEntities.BON_USR_USERS.Where(x => x.userName == userName && x.password == password).FirstOrDefault();
        }

        /// <summary>
        /// Method to clean sessions and redirct to the login View
        /// </summary>
        /// <returns>View</returns>
        public ActionResult Logout()
        {
            Session["userZitro"] = "";
            Session["expireZitroUser"] = "";
            return View("../Zitro/Index");
        }
    }
}

GatewayBelizeOn/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Belizeon - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top bon-navbar">
        <div class="container bon-header">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("belizeOn", "Index", "Zitro", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Zitro", "Index", "Zitro")</li>
                </ul>
                @if ((string)(Session["userZitro"]) != null && (string)(Session["userZitro"]) != "")
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("LogOut", "Logout", "Zitro")</li>
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
        <footer class="navbar-fixed-bottom text-center" style="background:#182e49; color: #FFF;padding-top:1.5rem;">
            <p>&copy; @DateTime.Now.Year - BelizeOn Powered By Socias Ltd</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/beonglobal")
    @RenderSection("scripts", required: false)
</body>
</html>